name: Build Flatpak Bundle

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  flatpak:
    name: Build Flatpak Application
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"

      - name: Generate requirements.txt
        run: |
          uv export --format requirements-txt --no-editable --no-dev \
            > requirements.txt

      - name: Vendor Python Dependencies
        run: |
          mkdir -p vendor-wheels
          uv build
          uv run pip download \
            dist/*.whl \
            -d vendor-wheels

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: packaging/flatpak/io.github.city_of_memphis_wastewater.maxson-gui-utils.yaml
          bundle: maxson-gui-utils.flatpak
          run-tests: false
          cache-key: flatpak-builder-${{ github.sha }}

      - name: Smoke test
        run: |
          flatpak install \
            --user \
            --bundle \
            --noninteractive \
            maxson-gui-utils.flatpak

          flatpak run io.github.city_of_memphis_wastewater.maxson-gui-utils --help
          flatpak run io.github.city_of_memphis_wastewater.maxson-gui-utils --version

      - name: Attach Flatpak to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v3
        with:
          files: "*.flatpak"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
