name: Run Tests

#on:
on: 
  push:
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  test:
    uses: City-of-Memphis-Wastewater/maxson-build-utils/.github/workflows/reusable-test.yml@main


